[package]
name = "shell"
version = "0.1.0"
authors = ["X-XG <9341624962@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.1.7"
